added server node model and registered models to admin
forgeno/CMPUT404-group-project pull request #104
Opened 2019-03-13 22:33 UTC by hiufungk

2019-03-14 02:27 UTC, forgeno approved these changes

2019-03-14 16:25 UTC, htruong4 requested changes

2019-03-14 16:25 UTC, htruong1 commented on backend/project_404_T5/settings.py
> +# these 2 URL should be changed when depolying
Can you leave a more detailed comment on what it has to be changed to in the case people don't know?

2019-03-15 02:34 UTC, htruong4 approved these changes

2019-03-15 02:34 UTC, merged