Redesign posts and pages
forgeno/CMPUT404-group-project pull request #122
Opened 2019-03-20 04:38 UTC by shchau

Added headers to pages. 
displayName for Author, Stream for Stream, Friends for Friends, Public for PublicStream.

Made it so auto-scroll in Author only happens upon clicking the Edit button.

Fixed visibility settings to handle private appropriately. 
Changed alerts to toasts. 

![Screenshot_2019-03-19_23-48-14](https://user-images.githubusercontent.com/31778426/54659443-34a99180-4aa8-11e9-8410-35e6c53f2e63.png)
![Screenshot_2019-03-19_23-48-33](https://user-images.githubusercontent.com/31778426/54659448-370beb80-4aa8-11e9-9d21-df6a521e8acf.png)
![Screenshot_2019-03-19_23-48-22](https://user-images.githubusercontent.com/31778426/54659449-37a48200-4aa8-11e9-85a7-1cbf973e2da7.png)
![Screenshot_2019-03-19_23-48-28](https://user-images.githubusercontent.com/31778426/54659450-37a48200-4aa8-11e9-83cd-3b4306a47b19.png)
![Screenshot_2019-03-19_23-48-41](https://user-images.githubusercontent.com/31778426/54659457-3a06dc00-4aa8-11e9-82b0-2befa037c173.png)
![Screenshot_2019-03-19_23-48-50](https://user-images.githubusercontent.com/31778426/54659458-3a06dc00-4aa8-11e9-959d-655a9a546078.png)

2019-03-20 07:05 UTC, hiufungk requested changes

2019-03-20 07:05 UTC, hiufungk commented on frontend/src/components/CreatePostModal.jsx
> +		var requestBody = {
why change from const to var

2019-03-20 07:05 UTC, hiufungk commented on frontend/src/components/CreatePostModal.jsx
> +				{this.state.createPostPageOne ?
no giant ternary expression please :'(

2019-03-20 07:05 UTC, hiufungk commented on frontend/src/components/StreamFeed.jsx
> +			key={payload.id}
some prop-types missing in stream post

2019-03-20 07:06 UTC, hiufungk commented
personally not a big fan of the text on top left corner. Maybe style the nav bar to indicate which page you are on instead?

2019-03-20 07:11 UTC, shchau commented on frontend/src/components/CreatePostModal.jsx
> +		var requestBody = {
Because then I can change visibleTo to be blank if visibility is not set to private. 
Lets user preserve previous visibleTo settings too.

2019-03-20 07:13 UTC, shchau commented on frontend/src/components/CreatePostModal.jsx
> +				{this.state.createPostPageOne ?
oml it just gets moved up but okay  
:'(

2019-03-20 07:26 UTC, shchau commented
> personally not a big fan of the text on top left corner. Maybe style the nav bar to indicate which page you are on instead?

Do you wanna restyle the Sidebar using your other version? :U 
I was also thinking of hiding the Sidebar in a button that has the text of the current thing you're on, but that'll take more work than we can afford atm probably.

2019-03-20 17:30 UTC, hiufungk approved these changes

2019-03-21 01:20 UTC, forgeno approved these changes

2019-03-21 01:20 UTC, merged