Comments Endpoint
forgeno/CMPUT404-group-project pull request #148
Opened 2019-03-25 04:19 UTC by htruong1

resolves #21

2019-03-25 19:18 UTC, shchau commented
Worked for me 👍

2019-03-26 00:02 UTC, hiufungk requested changes
waiting to have a common way of getting post id with other groups

2019-03-29 09:07 UTC, forgeno requested changes

2019-03-29 09:07 UTC, forgeno commented on backend/api/view/PostCommentsView.py
> +        if(local_post_filter.exists()):
Can you please add error checking

2019-03-29 09:07 UTC, forgeno commented on backend/api/view/PostCommentsView.py
> +                            author=request.data["comment"]["author"]["id"],
can you modulize `request.data["comment"]["author"]` and others

2019-03-29 09:07 UTC, forgeno commented on backend/api/view/PostCommentsView.py
> +                payload_author_id = request.data["comment"]["author"]["id"]
modulize this as well

2019-03-29 09:58 UTC, hiufungk approved these changes

2019-03-29 16:06 UTC, forgeno approved these changes

2019-03-29 16:14 UTC, hiufungk requested changes

2019-03-29 16:14 UTC, hiufungk commented on backend/api/view/StreamPostsView.py
> +                    if (can_read(user_id, post)):
check can read before preparing comments

2019-03-29 17:09 UTC, hiufungk approved these changes

2019-03-29 17:09 UTC, merged