Github activity in stream
forgeno/CMPUT404-group-project pull request #185
Opened 2019-03-30 18:23 UTC by derrick-w

Activity of users you follow on Github now appears in stream
Github rate limit workaround not implemented (Etag)

![Screenshot_20190330-1](https://user-images.githubusercontent.com/25085587/55280101-74614c00-52e6-11e9-8df7-6034dd9548c1.png)

2019-03-30 18:58 UTC, shchau commented on frontend/src/components/StreamPost.jsx
>  StreamPost.propTypes = {
Add isGithub as an non-required proptype. :+1:

2019-03-31 05:41 UTC, hiufungk requested changes

2019-03-31 05:41 UTC, hiufungk commented on frontend/src/pages/Author.jsx
> +    getFullAuthorIdFromURL(path) {
why is this unused function added？

2019-03-31 05:41 UTC, hiufungk commented on frontend/src/pages/Stream.jsx
> +		//todo deal with other hosts
why need to deal with other host?

2019-03-31 05:41 UTC, hiufungk commented on frontend/src/pages/Stream.jsx
> +		const hostUrl = "/api/author/"+ utils.getShortAuthorId(Cookies.get("userID")),
value from store || cookies.get instead of only cookie

2019-03-31 22:49 UTC, hiufungk approved these changes

2019-03-31 23:32 UTC, shchau approved these changes

2019-04-01 01:23 UTC, forgeno approved these changes

2019-04-01 02:40 UTC, merged