Register/Login API
forgeno/CMPUT404-group-project pull request #84
Opened 2019-03-10 07:14 UTC by forgeno

resolves #19 #25 #21 

Added front end and backend for login and register users. Tests are also added for each function.

2019-03-10 07:38 UTC, shchau commented
looks good to me

2019-03-10 07:48 UTC, htruong4 requested changes

2019-03-10 07:48 UTC, htruong1 commented on backend/api/view/RegistrationView.py
> +        # serializer = self.get_serializer(data=request.data)
remove comments please

2019-03-10 07:48 UTC, htruong1 commented on frontend/src/components/RegisterFormComponent.jsx
> +        // for (let stateKey in this.state) {
remove these comments pls

2019-03-10 07:48 UTC, htruong1 commented on frontend/src/components/RegisterFormComponent.jsx
> +            // return this.MessageExampleNegative("Failed to register", "Password entered does not match");
I'm not sure what is going on in this block. the statement is commented out?

2019-03-10 07:48 UTC, htruong1 commented on frontend/src/components/RegisterFormComponent.jsx
> +                {console.log((this.state.password === "" || this.state.password !== this.state.confirmpassword) && (this.state.displayName === "" || this.state.username === "") && this.state.loginAtt
remove this console.log

2019-03-10 07:48 UTC, htruong1 commented on frontend/src/pages/Login.jsx
> +        console.log(store.getState(), "your mom gay")
this is extremely offensive sir

2019-03-10 07:48 UTC, htruong1 commented on frontend/src/util/HTTPFetchUtil.js
> +        console.log("Checked and recieved auth")
remove this

2019-03-10 07:53 UTC, shchau commented on frontend/src/pages/Login.jsx
> +        console.log(store.getState(), "your mom gay")
your mom gay

2019-03-10 07:53 UTC, hiufungk requested changes

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/util/HTTPFetchUtil.js
> +        console.log("Checked and recieved auth")
remove this

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/pages/styles/Login.css
> +
remove this

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/pages/Login.jsx
> +
remove this

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/pages/Login.jsx
> +        console.log(store.getState(), "your mom gay")
remove this

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/actions/LoginActions.js
> +                        console.log(results)
remove this

2019-03-10 07:53 UTC, hiufungk commented on backend/api/serializers.py
> +    username = serializers.CharField()
this serializer is is not used, please remove it

2019-03-10 07:53 UTC, hiufungk commented on backend/api/tests/test_Login.py
> +        self.assertEqual(response.status_code, 400)
make it actually success by approving it

2019-03-10 07:53 UTC, hiufungk commented on backend/api/view/RegistrationView.py
> +        # serializer = self.get_serializer(data=request.data)
remove these comments

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/actions/RegisterActions.js
> +                console.log(httpResponse);
remove this

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/components/LoginFormComponent.jsx
> +                <Message negative hidden={!(this.state.loginAttempt > 0)}>
use <= instead

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/components/LoginFormComponent.jsx
> +                <Input error={false} type="text" placeholder="Username" onChange={this.handleChange} required/>
don't use error=false all the time

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/components/LoginFormComponent.jsx
> +                <Input error={false} type="password" placeholder="Password" onChange={this.handleChange} required/>
don't use error=false all the time

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/components/RegisterFormComponent.jsx
> +        // for (let stateKey in this.state) {
remove all these comments

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/components/RegisterFormComponent.jsx
> +        if (password !== confirmpassword) {
rewrite this to avoid having a blank if?

2019-03-10 07:53 UTC, hiufungk commented on frontend/src/components/RegisterFormComponent.jsx
> +                {console.log((this.state.password === "" || this.state.password !== this.state.confirmpassword) && (this.state.displayName === "" || this.state.username === "") && this.state.loginAtt
remove this

2019-03-10 23:55 UTC, shchau commented on frontend/src/pages/Login.jsx
> +        console.log(store.getState(), "your mom gay")
do not censor me sir

2019-03-11 00:58 UTC, hiufungk approved these changes

2019-03-11 03:53 UTC, htruong4 approved these changes

2019-03-11 03:55 UTC, merged