Basic stream post
forgeno/CMPUT404-group-project pull request #96
Opened 2019-03-13 04:26 UTC by shchau

Most functionality added. UI may be janky but haven't really gone to lengths with it yet. 

Some things in this branch are strictly related to displaying a post, please ignore those. 

Still need to handle source and origin, having an actual profile picture in the modal, and application/base64, and possibly some other stuff that I'm forgetting. 

Using store crashes the page so...login before trying to create a post.

2019-03-13 05:14 UTC, shchau commented on frontend/src/components/ProfileBubble.jsx
> +import './styles/ProfileBubble.css';
haha epic my dude

2019-03-13 05:38 UTC, derrick-w requested changes

2019-03-13 05:38 UTC, derrick-w commented on backend/api/view/LoginView.py
> +        print(request, "adgadfadfasfd")
xd

2019-03-13 05:38 UTC, derrick-w commented on frontend/src/components/CategoriesModal.jsx
> +				else {
xd dunno if you want this in master

2019-03-13 09:08 UTC, hiufungk commented
> Some things in this branch are strictly related to displaying a post, please ignore those.

instead of ignoring them, do not pull request the unrelated files

2019-03-13 09:09 UTC, hiufungk commented
> Still need to handle source and origin, having an actual profile picture in the modal, and application/base64, and possibly some other stuff that I'm forgetting.

add todo's to the mark down what needs to be done in the future

2019-03-13 09:25 UTC, hiufungk requested changes

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/actions/PostActions.js
> +	console.log(body);
remove this

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/actions/PostActions.js
> +                console.log(httpResponse);
remove this

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/components/AnimatedButton.jsx
> +			<div className="ui basic animated circular button removeBorder" tabIndex="0" onClick={this.props.clickFunction}>
add prop-types to components that depends on props as input

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/components/CategoriesModal.jsx
> +	handleAddition = (e, { value }) => {
change this to more descriptive name

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/components/CreatePostModal.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(CreatePostModal);
add prop types

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/components/VisibilitySettings.jsx
> +				}
add in error handling for non 200 response and display it

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/components/VisibilitySettings.jsx
> +		if (this.state.showModal === false) {
do !this.state.showModal instead？

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/components/CreatePostModal.jsx
> +		let $imagePreview = null;
why the "$"

2019-03-13 09:25 UTC, hiufungk commented on frontend/src/components/CreatePostModal.jsx
> +				origin: "http://localhost:8000",
add a todo indicating this has to change in the future

2019-03-13 15:18 UTC, shchau commented on frontend/src/components/CreatePostModal.jsx
> +		let $imagePreview = null;
Black magic.

2019-03-13 18:36 UTC, shchau commented
> > Some things in this branch are strictly related to displaying a post, please ignore those.
> 
> instead of ignoring them, do not pull request the unrelated files

No they make me feel the good and are harmless.

2019-03-13 18:51 UTC, derrick-w approved these changes

2019-03-14 01:03 UTC, hiufungk approved these changes

2019-03-14 01:22 UTC, forgeno requested changes

2019-03-14 01:22 UTC, forgeno commented on frontend/src/components/ProfileBubble.jsx
> +	profilePicture: "$No profile picture provided"
Please add comment why there is a "$" sign

2019-03-14 02:13 UTC, forgeno approved these changes

2019-03-14 02:15 UTC, merged